In [1]:
import pandas as pd
import numpy as np

Load Data

In [2]:
df = pd.read_csv('../data/customer_churn_dataset.csv')

3. Aperçu général du dataset

## 3.1 Affichage des premières lignes

In [3]:
df.head()

,Monthly_Usage,Customer_Support_Calls,Subscription_Length,Payment_Delay,Churn
0,122,6,48,6,1
1,455,2,39,3,0
2,368,5,29,25,1
3,290,1,42,20,1
4,126,9,55,17,1

Les 5 dernières lignes de l'ensemble de données

In [4]:
df.tail()

,Monthly_Usage,Customer_Support_Calls,Subscription_Length,Payment_Delay,Churn
195,190,0,10,20,1
196,48,7,26,21,1
197,55,0,34,21,1
198,32,8,51,2,1
199,179,5,41,15,0

## 3.2 Dimensions du dataset

In [5]:
print(f"\n• Number of rows    : {df.shape[0]}")
print(f"• Number of columns : {df.shape[1]}")
print(f"• Total cells       : {df.shape[0] * df.shape[1]}")

• Number of rows    : 200
• Number of columns : 5
• Total cells       : 1000

Liste des variables du dataset

In [6]:
df.columns.tolist()

['Monthly_Usage',
 'Customer_Support_Calls',
 'Subscription_Length',
 'Payment_Delay',
 'Churn']

## Types de données et valeurs manquantes

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Monthly_Usage           200 non-null    int64
 1   Customer_Support_Calls  200 non-null    int64
 2   Subscription_Length     200 non-null    int64
 3   Payment_Delay           200 non-null    int64
 4   Churn                   200 non-null    int64
dtypes: int64(5)
memory usage: 7.9 KB

 Statistiques descriptives des variables numériques

In [8]:
df.describe()

,Monthly_Usage,Customer_Support_Calls,Subscription_Length,Payment_Delay,Churn
count,200.000000,200.000000,200.000000,200.000000,200.000000
mean,260.555000,4.035000,31.170000,15.010000,0.685000
std,139.579508,2.901009,17.066559,8.462147,0.465682
min,21.000000,0.000000,1.000000,0.000000,0.000000
25%,149.500000,2.000000,16.000000,8.000000,0.000000
50%,260.500000,4.000000,31.500000,15.000000,1.000000
75%,379.000000,7.000000,46.250000,22.000000,1.000000
max,496.000000,9.000000,58.000000,29.000000,1.000000

Présence des valeurs manquantes

In [9]:
print(f"\nTotal missing values: {df.isnull().sum().sum()}")

df.isnull().sum().sort_values(ascending=False)

Total missing values: 0

Monthly_Usage             0
Customer_Support_Calls    0
Subscription_Length       0
Payment_Delay             0
Churn                     0
dtype: int64

Duplicates

In [10]:
print(f"Number of duplicate rows: {df.duplicated().sum()}")

df.duplicated()

Number of duplicate rows: 0

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

Variable cible : Churn

Distribution brute

In [11]:
print("Churn Distribution:")
print(df['Churn'].value_counts())

Churn Distribution:
Churn
1    137
0     63
Name: count, dtype: int64

Distribution en pourcentage

In [12]:
print("\nChurn Percentage:")
print(df['Churn'].value_counts(normalize=True) * 100)

Churn Percentage:
Churn
1    68.5
0    31.5
Name: proportion, dtype: float64

Comparison

In [13]:
print("Mean values by Churn status:")
df.groupby('Churn').mean()

Mean values by Churn status:

,Monthly_Usage,Customer_Support_Calls,Subscription_Length,Payment_Delay
Churn,,,,
0,261.746032,2.238095,31.047619,7.603175
1,260.007299,4.861314,31.226277,18.416058

Correlation

In [14]:
print("Correlation with Churn:")
df.corr()['Churn'].sort_values(ascending=False)

Correlation with Churn:

Churn                     1.000000
Payment_Delay             0.595045
Customer_Support_Calls    0.421089
Subscription_Length       0.004875
Monthly_Usage            -0.005801
Name: Churn, dtype: float64